#!/bin/bash

#Set GPIO for Lattice CPLD online upgrade function
echo 7 > /sys/class/gpio/export
echo 8 > /sys/class/gpio/export
echo 11 > /sys/class/gpio/export
echo 18 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio8/direction
echo out > /sys/class/gpio/gpio11/direction
echo out > /sys/class/gpio/gpio18/direction
echo in > /sys/class/gpio/gpio7/direction
