/*******************************************************************************
*              (c), Copyright 2001, Marvell International Ltd.                 *
* THIS CODE CONTAINS CONFIDENTIAL INFORMATION OF MARVELL SEMICONDUCTOR, INC.   *
* NO RIGHTS ARE GRANTED HEREIN UNDER ANY PATENT, MASK WORK RIGHT OR COPYRIGHT  *
* OF MARVELL OR ANY THIRD PARTY. MARVELL RESERVES THE RIGHT AT ITS SOLE        *
* DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.     *
* THIS CODE IS PROVIDED "AS IS". MARVELL MAKES NO WARRANTIES, EXPRESSED,       *
* IMPLIED OR OTHERWISE, REGARDING ITS ACCURACY, COMPLETENESS OR PERFORMANCE.   *
********************************************************************************
*/
/**
********************************************************************************
* @file prvCpssDxChHwTablesSip6.c
*
* @brief Private API implementation for tables access SIP6.
*
* @version   1
********************************************************************************
*/

#include <cpss/dxCh/dxChxGen/cpssHwInit/private/prvCpssDxChHwTables.h>
#include <cpss/dxCh/dxChxGen/config/private/prvCpssDxChInfo.h>


static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6FdbAuMsgTableFieldsFormat[SIP6_FDB_AU_MSG_TABLE_FIELDS___LAST_VALUE___E] =
{
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_MESSAGE_ID_E */
PRV_CPSS_STANDARD_FIELD_MAC(1)

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_MSG_TYPE_E */
,PRV_CPSS_STANDARD_FIELD_MAC(3)

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_FDB_ENTRY_TYPE_E */
,PRV_CPSS_STANDARD_FIELD_MAC(3)

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_VALID_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_SKIP_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_AGE _E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)


/*SIP6_FDB_AU_MSG_TABLE_FIELDS_CHAIN_TOO_LONG_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_OFFSET_E */
,PRV_CPSS_STANDARD_FIELD_MAC(5)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_UP0_E */
,PRV_CPSS_STANDARD_FIELD_MAC(3)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_E */
,PRV_CPSS_STANDARD_FIELD_MAC(48)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_DEV_ID_E */
,PRV_CPSS_STANDARD_FIELD_MAC(10)

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_FID_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(78,13)

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_IS_TRUNK_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(97,1)
    /*SIP6_FDB_AU_MSG_TABLE_FIELDS_EPORT_NUM_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     14,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_IS_TRUNK_E}

    /*SIP6_FDB_AU_MSG_TABLE_FIELDS_TRUNK_NUM_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     12,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_IS_TRUNK_E}

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_USER_DEFINED_10_7_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(93,4)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_USER_DEFINED_0_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(113,1)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_USER_DEFINED_4_1_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(114,4)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_USER_DEFINED_6_5_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(118,2)

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_SOURCE_ID_11_7_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(92,5)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_SOURCE_ID_6_3_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(114,4)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_SOURCE_ID_2_1_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(118,2)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_SOURCE_ID_0_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(120,1)

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_ORIG_VID1_11_7_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(92,5)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_ORIG_VID1_6_1_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(114,6)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_ORIG_VID1_0_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(120,1)


/*SIP6_FDB_AU_MSG_TABLE_FIELDS_APP_SPECIFIC_CPU_CODE_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(132,1)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_SP_UNKNOWN_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_IS_MOVED_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(135,1)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_IS_TRUNK_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*    SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_EPORT_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     14,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_IS_TRUNK_E}

/*    SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_TRUNK_NUM_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     12,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_IS_TRUNK_E}

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_DEVICE_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(152, 10)

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_SRC_ID_E */
,PRV_CPSS_STANDARD_FIELD_MAC(12)

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_IS_TRUNK_E  */
,PRV_CPSS_EXPLICIT_FIELD_MAC(96,1)
    /*SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_EPORT_NUM_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     14,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_IS_TRUNK_E}

    /*SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_TRUNK_NUM_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     12,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_IS_TRUNK_E}

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_USER_DEFINED_10_7_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(92,4)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_USER_DEFINED_0_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(112,1)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_USER_DEFINED_4_1_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(113,4)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_USER_DEFINED_6_5_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(117,2)

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_SOURCE_ID_11_7_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(91,5)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_SOURCE_ID_6_3_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(113,4)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_SOURCE_ID_2_1_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(117,2)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_SOURCE_ID_0_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(119,1)

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_ORIG_VID1_11_7_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(91,5)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_ORIG_VID1_6_1_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(113,6)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_ORIG_VID1_0_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(119,1)



/*****************************_E */
/* extra fields from 'MAC NA'_E */
/*****************************_E */

/*SIP6_FDB_AU_MSG_TABLE_FIELDS_VIDX_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(97,16)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_INDEX_8_0_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(10, 9)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_INDEX_20_9_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(135, 12)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_ENTRY_FOUND_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(16, 1)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_DIP_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(19, 32)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_SIP_26_0_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(51, 27)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_SIP_30_27_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(93, 4)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_SIP_31_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(147, 1)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_SA_ACCESS_LEVEL_E */
,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
 1,
 SIP6_FDB_AU_MSG_TABLE_FIELDS_FID_E}
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_DA_ACCESS_LEVEL_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_SEARCH_TYPE_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(134, 1)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_MULTIPLE_E */
,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
 1,
 SIP6_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_INDEX_20_9_E}
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_DA_ROUTE_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_IS_STATIC_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(155, 1)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_DA_CMD_E */
,PRV_CPSS_STANDARD_FIELD_MAC(2)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_SA_CMD_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(159, 1)
/*SIP6_FDB_AU_MSG_TABLE_FIELDS_FDB_LOOKUP_KEY_MODE_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(164, 1)

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_MAC_ADDR_INDEX_20_9_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(19,12)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_VRF_ID_E */
,PRV_CPSS_STANDARD_FIELD_MAC(12)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV4_DIP_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     32,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_VRF_ID_E}

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_FCOE_D_ID_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     24,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_VRF_ID_E}

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_SCOPE_CHECK_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     1,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_VRF_ID_E}
    /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_DST_SITE_ID_E */
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_127_106_E */
    ,PRV_CPSS_STANDARD_FIELD_MAC(22)

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_DEC_TTL_OR_HOP_COUNT_E */
,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
 1,
 SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV4_DIP_E}
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_BYPASS_TTL_OPTIONS_OR_HOP_EXTENSION_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_COUNTER_SET_INDEX_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(93,2)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_ICMP_REDIRECT_EXCEP_MIRROR_EN_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(103,1)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_MTU_INDEX_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_USE_VIDX_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(107,1)
    /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_EVIDX_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     16,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_USE_VIDX_E}

    /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IS_TRUNK_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     1,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_USE_VIDX_E}

        /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TARGET_DEVICE_E */
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         10,
         SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IS_TRUNK_E}
        /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_EPORT_NUM_E */
        ,PRV_CPSS_STANDARD_FIELD_MAC(14)

        /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TRUNK_NUM_E */
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         12,
         SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IS_TRUNK_E}

    /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ECMP_POINTER_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     15,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_EPORT_NUM_E}

    /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_NEXT_HOP_EVLAN_E */
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     13,
     SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_EPORT_NUM_E}
    /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_START_OF_TUNNEL_E */
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)

        /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_ARP_PTR_E */
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         18,
         SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_START_OF_TUNNEL_E}

        /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TUNNEL_TYPE_E */
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         1,
         SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_START_OF_TUNNEL_E}
        /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TUNNEL_PTR_E */
        ,PRV_CPSS_STANDARD_FIELD_MAC(16)
        /*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TS_IS_NAT_E */
        ,PRV_CPSS_STANDARD_FIELD_MAC(1)

/*,SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_ROUTE_TYPE_E */
,PRV_CPSS_STANDARD_FIELD_MAC(1)

    /***************************/
    /* ipv6 key routing fields */
    /***************************/

/*,SIP6_FDB_AU_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_31_0_E */
,PRV_CPSS_EXPLICIT_FIELD_MAC(31,32)
/*,SIP6_FDB_AU_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_63_32_E */
,PRV_CPSS_STANDARD_FIELD_MAC(32)
/*,SIP6_FDB_AU_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_95_64_E */
,PRV_CPSS_STANDARD_FIELD_MAC(32)
/*,SIP6_FDB_AU_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_105_96_E */
,PRV_CPSS_STANDARD_FIELD_MAC(10)

};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6FdbFdbTableFieldsFormat[SIP6_FDB_FDB_TABLE_FIELDS___LAST_VALUE___E] =
{
    /*SIP6_FDB_FDB_TABLE_FIELDS_VALID_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_SKIP_E  */
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_AGE_E   */
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_FDB_ENTRY_TYPE_E   */
    ,PRV_CPSS_STANDARD_FIELD_MAC(3)
    /*SIP6_FDB_FDB_TABLE_FIELDS_FID_E              */
    ,PRV_CPSS_STANDARD_FIELD_MAC(13)

    /*    SIP6_FDB_FDB_TABLE_FIELDS_MAC_ADDR_E     */
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         48,
         SIP6_FDB_FDB_TABLE_FIELDS_FID_E}
    /*    SIP6_FDB_FDB_TABLE_FIELDS_DEV_ID_E       */
        ,PRV_CPSS_STANDARD_FIELD_MAC(10)
    /*    SIP6_FDB_FDB_TABLE_FIELDS_SA_ACCESS_LEVEL_E          */
        ,PRV_CPSS_STANDARD_FIELD_MAC(1)


    /*    SIP6_FDB_FDB_TABLE_FIELDS_DIP_E          */
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         32,
         SIP6_FDB_FDB_TABLE_FIELDS_FID_E}
    /*    SIP6_FDB_FDB_TABLE_FIELDS_SIP_26_0_E          */
        ,PRV_CPSS_STANDARD_FIELD_MAC(27)

    /*SIP6_FDB_FDB_TABLE_FIELDS_DA_ACCESS_LEVEL_E*/
    ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     1,
     SIP6_FDB_FDB_TABLE_FIELDS_SA_ACCESS_LEVEL_E}

    /*SIP6_FDB_FDB_TABLE_FIELDS_ORIG_VID1_11_7_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(78,5)
    /*SIP6_FDB_FDB_TABLE_FIELDS_ORIG_VID1_6_1_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(100,6)
    /*SIP6_FDB_FDB_TABLE_FIELDS_ORIG_VID1_0_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(107,1)

    /*SIP6_FDB_FDB_TABLE_FIELDS_SOURCE_ID_11_7_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(78,5)
    /*SIP6_FDB_FDB_TABLE_FIELDS_SOURCE_ID_6_3_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(100,4)
    /*SIP6_FDB_FDB_TABLE_FIELDS_SOURCE_ID_2_1_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(104,2)
    /*SIP6_FDB_FDB_TABLE_FIELDS_SOURCE_ID_0_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(107,1)

    /*SIP6_FDB_FDB_TABLE_FIELDS_USER_DEFINED_10_7_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(79,4)
    /*SIP6_FDB_FDB_TABLE_FIELDS_USER_DEFINED_0_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(99,1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_USER_DEFINED_4_1_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(100,4)
    /*SIP6_FDB_FDB_TABLE_FIELDS_USER_DEFINED_6_5_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(104,2)

    /*SIP6_FDB_FDB_TABLE_FIELDS_SIP_30_27_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(79,4)

    /*SIP6_FDB_FDB_TABLE_FIELDS_VIDX_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(83,16)

    /*SIP6_FDB_FDB_TABLE_FIELDS_IS_TRUNK_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(83,1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_TRUNK_NUM_E*/
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         12,
         SIP6_FDB_FDB_TABLE_FIELDS_IS_TRUNK_E}

    /*SIP6_FDB_FDB_TABLE_FIELDS_EPORT_NUM_E*/
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         14,
         SIP6_FDB_FDB_TABLE_FIELDS_IS_TRUNK_E}


        /*SIP6_FDB_FDB_TABLE_FIELDS_SIP_31_E*/
        ,PRV_CPSS_EXPLICIT_FIELD_MAC(106,1)

        /*SIP6_FDB_FDB_TABLE_FIELDS_MULTIPLE_E*/
        ,PRV_CPSS_EXPLICIT_FIELD_MAC(106,1)

    /*SIP6_FDB_FDB_TABLE_FIELDS_IS_STATIC_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(108,1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_DA_CMD_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(2)
    /*SIP6_FDB_FDB_TABLE_FIELDS_SA_CMD_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_DA_ROUTE_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_SP_UNKNOWN_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_APP_SPECIFIC_CPU_CODE_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)

    /**********************************/
    /* ipv4/6 and fcoe routing fields */
    /**********************************/
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_VRF_ID_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(6,12)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_IPV4_DIP_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(18,32)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_FCOE_D_ID_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(18,24)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_IPV6_SCOPE_CHECK_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(18,1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_IPV6_DST_SITE_ID_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_127_106_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(22)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_DEC_TTL_OR_HOP_COUNT_E*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(50,1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_BYPASS_TTL_OPTIONS_OR_HOP_EXTENSION_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_COUNTER_SET_INDEX_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(2)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_ICMP_REDIRECT_EXCEPTION_MIRROR_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_MTU_INDEX_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_USE_VIDX_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_EVIDX_E*/
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         16,
         SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_USE_VIDX_E}
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TRG_IS_TRUNK_E*/
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         1,
         SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_USE_VIDX_E}
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TRG_EPORT_E*/
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         14,
         SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TRG_IS_TRUNK_E}
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TRG_TRUNK_ID_E*/
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         12,
         SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TRG_IS_TRUNK_E}
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TRG_DEV_E*/
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         10,
         SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TRG_EPORT_E}

    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_ECMP_POINTER_E*/
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         15,
         SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TRG_DEV_E}
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_NEXT_HOP_EVLAN_E*/
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         13,
         SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TRG_DEV_E}
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_START_OF_TUNNEL_E*/
        ,PRV_CPSS_STANDARD_FIELD_MAC(1)

    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_ARP_PTR_E*/
            ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
             18,
             SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_START_OF_TUNNEL_E}

    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TUNNEL_TYPE_E*/
            ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
             1,
             SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_START_OF_TUNNEL_E}
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TUNNEL_PTR_E*/
            ,PRV_CPSS_STANDARD_FIELD_MAC(16)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_TS_IS_NAT_E*/
            ,PRV_CPSS_STANDARD_FIELD_MAC(1)

    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_ROUTE_TYPE_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)

    /********************************/
    /* ipv6 key routing fields      */
    /********************************/
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_31_0*/
    ,PRV_CPSS_EXPLICIT_FIELD_MAC(6,32)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_63_32*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(32)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_95_64*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(32)
    /*SIP6_FDB_FDB_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_105_96*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(10)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6L2iIngressVlanTableFieldsFormat[
SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS___LAST_VALUE___E] =
{
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_VALID_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_NEW_SRC_ADDR_IS_NOT_SECURITY_BREACH_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UNREGISTERED_NON_IP_MULTICAST_CMD_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UNREGISTERED_IPV4_MULTICAST_CMD_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UNREGISTERED_IPV6_MULTICAST_CMD_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UNKNOWN_UNICAST_CMD_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV4_IGMP_TO_CPU_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV4_IPM_BRIDGING_MODE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV6_IPM_BRIDGING_MODE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_MIRROR_TO_INGRESS_ANALYZER_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV6_ICMP_TO_CPU_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV4_CONTROL_TO_CPU_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV4_IPM_BRIDGING_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV6_IPM_BRIDGING_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UNREGISTERED_IPV4_BC_CMD_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UNREGISTERED_NON_IPV4_BC_CMD_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV4_UNICAST_ROUTE_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV4_MULTICAST_ROUTE_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV6_UNICAST_ROUTE_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV6_MULTICAST_ROUTE_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV6_SITEID_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_AUTO_LEARN_DIS_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_NA_MSG_TO_CPU_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_MRU_INDEX_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_BC_UDP_TRAP_MIRROR_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV6_CONTROL_TO_CPU_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_FLOOD_EVIDX_E */
    PRV_CPSS_STANDARD_FIELD_MAC(16),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_VRF_ID_E */
    PRV_CPSS_STANDARD_FIELD_MAC(0),/* sip6 : moved this field to TTI unit (new table entry per vlan) */
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UC_LOCAL_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_FLOOD_VIDX_MODE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV4_MC_BC_TO_MIRROR_ANLYZER_IDX_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_IPV6_MC_TO_MIRROR_ANALYZER_IDX_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_FID_E */
    PRV_CPSS_STANDARD_FIELD_MAC(13),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UNKOWN_MAC_SA_CMD_E */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_FCOE_FORWARDING_EN_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UNREG_IPM_EVIDX_MODE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_UNREG_IPM_EVIDX_E */
    PRV_CPSS_STANDARD_FIELD_MAC(16),
    /* SIP5_L2I_INGRESS_VLAN_TABLE_FIELDS_FDB_LOOKUP_KEY_MODE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1)
};


typedef struct{
    SIP5_FDB_AU_MSG_TABLE_FIELDS_ENT    sip5Field;
    SIP6_FDB_AU_MSG_TABLE_FIELDS_ENT    sip6Field;
}CONVERT_SIP5_TO_SIP6_FDB_AU_MSG;

#define NOT_VALID_FIELD_CNS 0xFFFFFFFF
/* table that hold the relation between fields from SIP5 to those in SIP6 */
/* this table will allow most of the SIP5 code to keep using call to :
    SIP5_FDB_AU_MSG_FIELD_GET_MAC(with sip5 SIP5_FDB_AU_MSG_TABLE_FIELDS_xxx field)
    SIP5_FDB_AU_MSG_FIELD_SET_MAC(with sip5 SIP5_FDB_AU_MSG_TABLE_FIELDS_xxx field)

    without the need to duplicate it for SIP6 notation.

*/
static CONVERT_SIP5_TO_SIP6_FDB_AU_MSG convertSip5ToSip6FdbAuMsgArr[] =
{
     {SIP5_FDB_AU_MSG_TABLE_FIELDS_MESSAGE_ID_E                                    ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_MESSAGE_ID_E                          }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_MSG_TYPE_E                                      ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_MSG_TYPE_E                            }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_FDB_ENTRY_TYPE_E                                ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_FDB_ENTRY_TYPE_E                      }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_VALID_E                                         ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_VALID_E                               }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SKIP_E                                          ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_SKIP_E                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_AGE_E                                           ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_AGE_E                                 }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_INDEX_8_0_E                            ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_INDEX_8_0_E                  }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_CHAIN_TOO_LONG_E                                ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_CHAIN_TOO_LONG_E                      }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_OFFSET_E                               ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_OFFSET_E                     }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_ENTRY_FOUND_E                                   ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_ENTRY_FOUND_E                         }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_E                                      ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_E                            }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_DEV_ID_E                                        ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_DEV_ID_E                              }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SOURCE_ID_5_0_E                                 ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_DIP_E                                           ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_DIP_E                                 }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SIP_E                                           ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_FID_E                                           ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_FID_E                                 }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_VIDX_E                                          ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_VIDX_E                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_IS_TRUNK_E                                      ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_IS_TRUNK_E                            }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_EPORT_NUM_E                                     ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_EPORT_NUM_E                           }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_TRUNK_NUM_E                                     ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_TRUNK_NUM_E                           }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_USER_DEFINED_E                                  ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_RESERVED_109_113_E                              ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SOURCE_ID_11_9_E                                ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_ORIG_VID1_E                                     ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_DA_ACCESS_LEVEL_E                               ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_DA_ACCESS_LEVEL_E                     }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SA_ACCESS_LEVEL_E                               ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_SA_ACCESS_LEVEL_E                     }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SOURCE_ID_8_6_E                                 ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_APP_SPECIFIC_CPU_CODE_E                         ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_APP_SPECIFIC_CPU_CODE_E               }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SP_UNKNOWN_E                                    ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_SP_UNKNOWN_E                          }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SEARCH_TYPE_E                                   ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_SEARCH_TYPE_E                         }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_INDEX_20_9_E                           ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_MAC_ADDR_INDEX_20_9_E                 }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_MULTIPLE_E                                      ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_MULTIPLE_E                            }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_DA_ROUTE_E                                      ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_DA_ROUTE_E                            }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SA_QOS_PARAM_SET_IDX_E                          ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_DA_QOS_PARAM_SET_IDX_E                          ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_IS_STATIC_E                                     ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_IS_STATIC_E                           }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_DA_CMD_E                                        ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_DA_CMD_E                              }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SA_CMD_E                                        ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_SA_CMD_E                              }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_SA_LOOKUP_INGRESS_MIRROR_TO_ANALYZER_E          ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_DA_LOOKUP_INGRESS_MIRROR_TO_ANALYZER_E          ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_FDB_LOOKUP_KEY_MODE_E                           ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_FDB_LOOKUP_KEY_MODE_E                 }

    /* additions for the  format of : MAC NA moved update Message */
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_UP0_E                                  ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_UP0_E                        }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_IS_MOVED_E                             ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_IS_MOVED_E                   }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_IS_TRUNK_E                         ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_IS_TRUNK_E               }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_EPORT_E                            ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_EPORT_E                  }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_TRUNK_NUM_E                        ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_TRUNK_NUM_E              }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_DEVICE_E                           ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_DEVICE_E                 }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_SRC_ID_E                           ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_NA_MOVED_OLD_SRC_ID_E                 }

    /* fields for FDB Routing */
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_MAC_ADDR_INDEX_E                       ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_VRF_ID_E                               ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_VRF_ID_E                     }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_SCOPE_CHECK_E                     ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_SCOPE_CHECK_E           }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_FCOE_D_ID_E                            ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_FCOE_D_ID_E                  }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV4_DIP_E                             ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV4_DIP_E                   }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_DST_SITE_ID_E                     ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_DST_SITE_ID_E           }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_DEC_TTL_OR_HOP_COUNT_E                 ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_DEC_TTL_OR_HOP_COUNT_E       }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_BYPASS_TTL_OPTIONS_OR_HOP_EXTENSION_E  ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_BYPASS_TTL_OPTIONS_OR_HOP_EXTENSION_E}
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_INGRESS_MIRROR_TO_ANALYZER_INDEX_E     ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_QOS_PROFILE_MARKING_EN_E               ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_QOS_PROFILE_INDEX_E                    ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_QOS_PROFILE_PRECEDENCE_E               ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_MODIFY_UP_E                            ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_MODIFY_DSCP_E                          ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_COUNTER_SET_INDEX_E                    ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_COUNTER_SET_INDEX_E          }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_ARP_BC_TRAP_MIRROR_EN_E                ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_DIP_ACCESS_LEVEL_E                     ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_ICMP_REDIRECT_EXCEP_MIRROR_EN_E        ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_ICMP_REDIRECT_EXCEP_MIRROR_EN_E}
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_MTU_INDEX_E                            ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_MTU_INDEX_E                  }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_USE_VIDX_E                             ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_USE_VIDX_E                   }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IS_TRUNK_E                             ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IS_TRUNK_E                   }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_EVIDX_E                                ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_EVIDX_E                      }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TARGET_DEVICE_E                        ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TARGET_DEVICE_E              }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TRUNK_NUM_E                            ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TRUNK_NUM_E                  }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_EPORT_NUM_E                            ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_EPORT_NUM_E                  }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_NEXT_HOP_EVLAN_E                       ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_NEXT_HOP_EVLAN_E             }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TUNNEL_START_E                         ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_START_OF_TUNNEL_E            }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TUNNEL_TYPE_E                          ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TUNNEL_TYPE_E                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_ARP_PTR_E                              ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_ARP_PTR_E                    }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TUNNEL_PTR_E                           ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TUNNEL_PTR_E                 }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_0_E                           ,   SIP6_FDB_AU_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_31_0_E                  }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_1_E                           ,   SIP6_FDB_AU_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_63_32_E                 }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_2_E                           ,   SIP6_FDB_AU_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_95_64_E                 }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_IPV6_DIP_3_E                           ,   NOT_VALID_FIELD_CNS                                                }
    ,{SIP5_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_NH_DATA_BANK_NUM_E                     ,   NOT_VALID_FIELD_CNS                                                }

    ,{SIP5_10_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TS_IS_NAT_E                         ,   SIP6_FDB_AU_MSG_TABLE_FIELDS_UC_ROUTE_TS_IS_NAT_E                  }

    /* must be last */
    ,{SIP5_10_FDB_AU_MSG_TABLE_FIELDS___LAST_VALUE___E , SIP6_FDB_AU_MSG_TABLE_FIELDS___LAST_VALUE___E}
};

/* the table emulate fields from SIP5 to those of SIP6 */
/* this table will allow most of the SIP5 code to keep using call to :
    SIP5_FDB_AU_MSG_FIELD_GET_MAC(with sip5 SIP5_FDB_AU_MSG_TABLE_FIELDS_xxx field)
    SIP5_FDB_AU_MSG_FIELD_SET_MAC(with sip5 SIP5_FDB_AU_MSG_TABLE_FIELDS_xxx field)

    without the need to duplicate it for SIP6 notation.
*/
static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip5_emulate_Sip6FdbAuMsgTableFieldsFormat[SIP5_10_FDB_AU_MSG_TABLE_FIELDS___LAST_VALUE___E];
/*
    NOTE: filled in runtime with info from prvCpssDxChSip6FdbAuMsgTableFieldsFormat according to field converted using convertSip5ToSip6FdbAuMsgArr
*/


/* SIP6 PREQ tables fields */
static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6PreqPortProfileTableFieldsFormat[
    SIP6_PREQ_PORT_PROFILE_TABLE_FIELDS___LAST_VALUE___E]=
{
    /*SIP6_PREQ_PORT_PROFILE_TABLE_FIELDS_TD_DYNAMIC_FACTOR_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(4),
    /*SIP6_PREQ_PORT_PROFILE_TABLE_FIELDS_TD_GUARANTIED_LIMIT_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_PORT_PROFILE_TABLE_FIELDS_TD_DROP_PROBABILITY_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP6_PREQ_PORT_PROFILE_TABLE_FIELDS_TD_WRED_SIZE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_PORT_PROFILE_TABLE_FIELDS_PORT_QCN_DYNAMIC_FACTOR_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_PORT_PROFILE_TABLE_FIELDS_QCN_LIMIT_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_PORT_PROFILE_TABLE_FIELDS_CN_AWARE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP6_PREQ_PORT_PROFILE_TABLE_FIELDS_PORT_STATUS_LIMIT_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6PreqProfilesTableFieldsFormat[
    SIP6_PREQ_PROFILES_TABLE_FIELDS___LAST_VALUE___E]=
{
    /*SIP6_PREQ_PROFILES_TABLE_FIELDS_QUEUE_MAX_LIMIT_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_PROFILES_TABLE_FIELDS_QUEUE_QCN_DYNAMIC_FACTOR_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(4),
    /*SIP6_PREQ_PROFILES_TABLE_FIELDS_QCN_LIMIT_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_PROFILES_TABLE_FIELDS_CN_AWARE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP6_PREQ_PROFILES_TABLE_FIELDS_TELEMETRY_SELECT_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP6_PREQ_PROFILES_TABLE_FIELDS_QUEUE_OCCUPANCY_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_PROFILES_TABLE_FIELDS_TELEMETRY_QUEUE_LIMIT_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_PROFILES_TABLE_FIELDS_QUEUE_STATUS_LIMIT_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6PreqQueueConfigurationsTableFieldsFormat[
    SIP6_PREQ_QUEUE_CONFIGURATIONS_TABLE_FIELDS___LAST_VALUE___E]=
{
    /*SIP6_PREQ_QUEUE_CONFIGURATIONS_TABLE_FIELDS_TD_DYNAMIC_FACTOR_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(4),
    /*SIP6_PREQ_QUEUE_CONFIGURATIONS_TABLE_FIELDS_TD_GUARANTIED_LIMIT_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_QUEUE_CONFIGURATIONS_TABLE_FIELDS_TD_DROP_PROBABILITY_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP6_PREQ_QUEUE_CONFIGURATIONS_TABLE_FIELDS_TD_WRED_SIZE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
    /*SIP6_PREQ_QUEUE_CONFIGURATIONS_TABLE_FIELDS_ECN_ENABLE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6PreqQueuePortMappingTableFieldsFormat[
    SIP6_PREQ_QUEUE_PORT_MAPPING_TABLE_FIELDS___LAST_VALUE___E]=
{
    /*SIP6_PREQ_QUEUE_PORT_MAPPING_TABLE_FIELDS_PASS_DROP_PORT_BASE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(13),
    /*SIP6_PREQ_QUEUE_PORT_MAPPING_TABLE_FIELDS_STATUS_PORT_BASE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(13)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6PreqQueuePrioMappingTableFieldsFormat[
    SIP6_PREQ_QUEUE_PRIO_MAPPING_TABLE_FIELDS___LAST_VALUE___E]=
{
    /*SIP6_PREQ_QUEUE_PRIO_MAPPING_TABLE_FIELDS_QUEUE_PRIO_PROFILE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(4)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6PreqTargetPhysicalPortFieldsFormat[
    SIP6_PREQ_TARGET_PHYSICAL_PORT_TABLE_FIELDS___LAST_VALUE___E]=
{
    /*SIP6_PREQ_TARGET_PHYSICAL_PORT_TABLE_FIELDS_VLAN_COUNTING_ENABLE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP6_PREQ_TARGET_PHYSICAL_PORT_TABLE_FIELDS_EGRESS_MIRRORING_CODE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP6_PREQ_TARGET_PHYSICAL_PORT_TABLE_FIELDS_EGRESS_ANALYZER_INDEX_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(3)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6EgfQagPortTargetAttributesTableFieldsFormat[
    SIP5_20_EGF_QAG_PORT_TARGET_ATTRIBUTES_TABLE_FIELDS___LAST_VALUE___E] =
{
    /*SIP5_20_EGF_QAG_PORT_TARGET_ATTRIBUTES_TABLE_FIELDS_ETARGET_PHYSICAL_PORT_LOOPBACK_PROFILE_E       */
    PRV_CPSS_STANDARD_FIELD_MAC(2)
    /*SIP5_20_EGF_QAG_PORT_TARGET_ATTRIBUTES_TABLE_FIELDS_ETARGET_PHYSICAL_PORT_TC_PROFILE_E             */
   ,PRV_CPSS_STANDARD_FIELD_MAC(4)/*changed in sip6 to 4*/
    /*SIP5_20_EGF_QAG_PORT_TARGET_ATTRIBUTES_TABLE_FIELDS_ETARGET_PHYSICAL_PORT_EVLAN_MIRRORING_ENABLE_E */
   ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP5_20_EGF_QAG_PORT_TARGET_ATTRIBUTES_TABLE_FIELDS_EUSE_VLAN_TAG_1_FOR_TAG_STATE_E                */
   ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP5_20_EGF_QAG_PORT_TARGET_ATTRIBUTES_TABLE_FIELDS_ETARGET_PHYSICAL_PORT_ENQ_PROFILE_E            */
   ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP5_20_EGF_QAG_PORT_TARGET_ATTRIBUTES_TABLE_FIELDS_ELOOPBACK_ENQ_PROFILE_E                        */
   ,PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP5_20_EGF_QAG_PORT_TARGET_ATTRIBUTES_TABLE_FIELDS_ELOOPBACK_PORT_E                               */
   ,PRV_CPSS_STANDARD_FIELD_MAC(10)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6TtiPhysicalPortTableFieldsFormat[SIP6_TTI_PHYSICAL_PORT_TABLE_FIELDS___LAST_VALUE___E] =
{
/* SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_PORT_DEFAULT_SOURCE_EPORT_NUMBER_E */
    PRV_CPSS_STANDARD_FIELD_MAC(13),  /*-1 from sip5_10*/
/* SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_PORT_IS_RING_CORE_PORT_E */
    PRV_CPSS_STANDARD_FIELD_MAC(0),
/* SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_PORT_IS_LOOPED_E */
    PRV_CPSS_EXPLICIT_FIELD_MAC(14,1),
/* SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_ENABLE_MRU_CHECK_ON_CASCADE_PORT_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/* SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_CC_LINE_CARD_PORTS_DEFAULT_EPORT_BASE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(14),  /*+1 from sip5_10*/
/* SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_CC_LINE_CARD_TRUNK_DEFAULT_EPORT_BASE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(14),  /*+1 from sip5_10*/
/* SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_CENTRALIZED_CHASSIS_PORT_ENABLE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/* SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_TRUNK_ID_E */
    PRV_CPSS_STANDARD_FIELD_MAC(12),
/* SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_PORT_QOS_MODE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/* SIP6_TTI_PHYSICAL_PORT_TABLE_FIELDS_ACCEPT_EDSA_SKIP_FDB_SA_LOOKUP_FIELD_E */
    {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
     1,
     SIP5_TTI_PHYSICAL_PORT_TABLE_FIELDS_PORT_DEFAULT_SOURCE_EPORT_NUMBER_E}
};


static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6IpclActionTableFieldsFormat[SIP6_IPCL_ACTION_TABLE_FIELDS___LAST_VALUE___E] =
{
/*SIP6_IPCL_ACTION_TABLE_FIELDS_CPU_CODE*/
    PRV_CPSS_STANDARD_FIELD_MAC(8),
/*SIP5_20_IPCL_ACTION_TABLE_FIELDS_COMMAND*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_REDIRECT_COMMAND*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_ACTION_STOP*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_SET_MAC2ME*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*==================*/
    /*If <Redirect Command> = No Redirect (0)*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_POLICY1_LOOKUP_MODE*/
        {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         1,
         SIP6_IPCL_ACTION_TABLE_FIELDS_SET_MAC2ME_E},
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_POLICY2_LOOKUP_MODE*/
        PRV_CPSS_STANDARD_FIELD_MAC(1),
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_IPCL_PROFILE_INDEX*/
        PRV_CPSS_STANDARD_FIELD_MAC(13),
    /*==================*/
    /* If <Redirect Command> = 1 (Redirect to egress interface)*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_USE_VIDX*/
        {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         1,
         SIP6_IPCL_ACTION_TABLE_FIELDS_SET_MAC2ME_E},
         /*<UseVIDX> = 1*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_VIDX*/
        PRV_CPSS_STANDARD_FIELD_MAC(16),
         /*if <UseVIDX> = 0*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_IS_TRUNK*/
            {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
             1,
             SIP6_IPCL_ACTION_TABLE_FIELDS_USE_VIDX_E},
            /*if <UseVIDX> = 0 & <IsTrunk> = 0*/
            /*SIP6_IPCL_ACTION_TABLE_FIELDS_TRG_PORT*/
                {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
                 14,
                 SIP6_IPCL_ACTION_TABLE_FIELDS_IS_TRUNK_E},
            /*SIP6_IPCL_ACTION_TABLE_FIELDS_TARGET_DEVICE*/
            PRV_CPSS_STANDARD_FIELD_MAC(10),
            /*if <UseVIDX> = 0 & <IsTrunk> = 1*/
            /*SIP6_IPCL_ACTION_TABLE_FIELDS_TRUNK_ID*/
            {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
             14,
             SIP6_IPCL_ACTION_TABLE_FIELDS_IS_TRUNK_E},
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_VNT_L2_ECHO*/
        {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         1,
         SIP6_IPCL_ACTION_TABLE_FIELDS_TARGET_DEVICE_E},
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_TUNNEL_START*/
        PRV_CPSS_STANDARD_FIELD_MAC(1),
            /*if <Tunnel Start> == 0*/
            /*SIP6_IPCL_ACTION_TABLE_FIELDS_ARP_POINTER*/
            {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
             18,
             SIP6_IPCL_ACTION_TABLE_FIELDS_TUNNEL_START_E},
            /*if <Tunnel Start> == 1*/
            /*SIP6_IPCL_ACTION_TABLE_FIELDS_TUNNEL_POINTER*/
            {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
             16,
             SIP6_IPCL_ACTION_TABLE_FIELDS_TUNNEL_START_E},
            /*SIP6_IPCL_ACTION_TABLE_FIELDS_TUNNEL_START_PASSENGER_TYPE*/
            PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*==================*/
    /*If <Redirect Command> = 2 (Redirect to NHE)*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_PBR_MODE*/
        PRV_CPSS_EXPLICIT_FIELD_MAC(32,1),
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_IP_NEXT_HOP_ENTRY_INDEX*/
        PRV_CPSS_STANDARD_FIELD_MAC(18),
    /*==================*/
    /*else if <Redirect Command> = 4 (Assign VRF_ID)*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_VRF_ID*/
        PRV_CPSS_EXPLICIT_FIELD_MAC(52,12),
    /*==================*/
    /*else if (<Redirect Command> = 6 - Replace MAC SA)*/
    /* 43 16 Mac Sa[27:0]
    Mac_Sa
     81 62 Mac Sa [47:28]
    Mac_Sa_47_28*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_MAC_SA_27_0*/
        {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         28,
         SIP6_IPCL_ACTION_TABLE_FIELDS_SET_MAC2ME_E},
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_MAC_SA_47_28*/
        PRV_CPSS_EXPLICIT_FIELD_MAC(62,20),
    /*==================*/

    /*else if (<Redirect Command> = !6 - Replace MAC SA)*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_ACTIVATE_METER*/
        PRV_CPSS_EXPLICIT_FIELD_MAC(64,1),
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_BIND_TO_POLICER_COUNTER*/
        PRV_CPSS_STANDARD_FIELD_MAC(1),
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_POLICER_PTR*/
        PRV_CPSS_STANDARD_FIELD_MAC(14),
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_RESERVED*/
        PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*==================*/
/*SIP6_IPCL_ACTION_TABLE_FIELDS_ENABLE_MIRROR_TCP_RST_OR_FIN*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_MIRROR_TO_ANALYZER_PORT*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_MODIFY_MAC_DA*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
        /*If <Redirect Command> = 1 (Redirect to egress interface)*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_MODIFY_MAC_SA*/
        {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         1,
         SIP6_IPCL_ACTION_TABLE_FIELDS_MODIFY_MAC_DA_E},
        /* If <Redirect Command> != 1 (Redirect to egress interface)*/
        /*SIP6_IPCL_ACTION_TABLE_FIELDS_SET_EGRESS_FILTER_REGISTERED*/
        {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
         1,
         SIP6_IPCL_ACTION_TABLE_FIELDS_MODIFY_MAC_DA_E},
/*SIP6_IPCL_ACTION_TABLE_FIELDS_BRIDGE_BYPASS*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_BYPASS_INGRESS_PIPE*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_EN_NESTED_VLAN*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_SET_SST_ID*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_SST_ID*/
    PRV_CPSS_STANDARD_FIELD_MAC(12),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_USER_AC_ENABLE*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_ACTIVATE_COUNTER*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_COUNTER_INDEX*/
    PRV_CPSS_STANDARD_FIELD_MAC(14),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_VLAN_PRECEDENCE*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_VLAN_COMMAND*/
    PRV_CPSS_STANDARD_FIELD_MAC(2),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_VID0*/
    PRV_CPSS_STANDARD_FIELD_MAC(13),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_QOS_PROFILE_MARKING_ENABLE*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_QOS_PRECEDENCE*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_QOS_PROFILE*/
    PRV_CPSS_STANDARD_FIELD_MAC(10),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_MODIFY_DSCP*/
    PRV_CPSS_STANDARD_FIELD_MAC(2),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_MODIFY_UP*/
    PRV_CPSS_STANDARD_FIELD_MAC(2),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_VLAN1_CMD*/
    PRV_CPSS_STANDARD_FIELD_MAC(2),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_UP1_CMD*/
    PRV_CPSS_STANDARD_FIELD_MAC(2),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_VID1*/
    PRV_CPSS_STANDARD_FIELD_MAC(12),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_UP1*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_IPCL_RESERVED_EN*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_IPCL_TO_TXQ_RESERVED*/
    PRV_CPSS_STANDARD_FIELD_MAC(20),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_TIMESTAMP_EN*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_OFFSET_INDEX*/
    PRV_CPSS_STANDARD_FIELD_MAC(7),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_OAM_PROCESSING_EN*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_OAM_PROFILE*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_FLOW_ID*/
    PRV_CPSS_STANDARD_FIELD_MAC(13),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_RESERVED_1*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_ASSIGN_SRC_EPORT_EN*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_SRC_EPORT*/
    PRV_CPSS_STANDARD_FIELD_MAC(14),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_LATENCY_PROFILE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(9),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_LATENCY_MONITORING_ENABLE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_SKIP_FDB_SA_LOOKUP_EN_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_TRIGGER_INTERRUPT_EN_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_RESERVED_3_BITS_E*/                              /*243-245*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*SIP6_IPCL_ACTION_TABLE_FIELDS_EXACT_MATCH_OVER_PCL_ENABLE_E*/                  /*246*/
    PRV_CPSS_STANDARD_FIELD_MAC(1)
};


static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6EpclActionTableFieldsFormat[
    SIP5_EPCL_ACTION_TABLE_FIELDS___LAST_VALUE___E] =
{
/*SIP5_EPCL_ACTION_TABLE_FIELDS_COMMAND_E                                   *//*0*/
     PRV_CPSS_STANDARD_FIELD_MAC(3 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_DSCP_EXP_E                                  *//*3*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(6 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_UP0_E                                       *//*9*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(3 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_MODIFY_DSCP_EXP_E                           *//*12*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(2 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_ENABLE_MODIFY_UP0_E                         *//*14*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(2 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_BIND_TO_CNC_COUNTER_E                       *//*16*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_CNC_COUNTER_INDEX_E                         *//*17*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(14)
/*SIP5_EPCL_ACTION_TABLE_FIELDS_TAG1_VID_CMD_E                              *//*31*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_ENABLE_MODIFY_UP1_E                         *//*32*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_TAG1_VID_E                                  *//*33*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(12)
/*SIP5_EPCL_ACTION_TABLE_FIELDS_UP1_E                                       *//*45*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(3 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_TAG0_VLAN_CMD_E                             *//*48*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(2 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_TAG0_VID_E                                  *//*50*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(12)
/*SIP5_EPCL_ACTION_TABLE_FIELDS_BIND_TO_POLICER_COUNTER_E                   *//*62*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_BIND_TO_POLICER_METER_E                     *//*63*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_POLICER_INDEX_E                             *//*64*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(14)/*increase by 1 */
/*SIP5_EPCL_ACTION_TABLE_FIELDS_RESERVED_E                                  *//*78*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(0) /*removed*/
/*SIP5_EPCL_ACTION_TABLE_FIELDS_FLOW_ID_E                                   *//*78*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(13)/*increase by 1*/
/*SIP5_EPCL_ACTION_TABLE_FIELDS_OAM_PROCESSING_ENABLE_E                     *//*91*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_OAM_PROFILE_E                               *//*92*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_TIME_STAMP_ENABLE_E                         *//*93*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_TIME_STAMP_OFFSET_INDEX_E                   *//*94*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(7 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_CHANNEL_TYPE_TO_OPCODE_MAPPING_EN_E         *//*101*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_EPCL_RESERVED_ENABLE_E                      *//*102*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1 )
/*SIP5_EPCL_ACTION_TABLE_FIELDS_EPCL_RESERVED_E                             *//*103*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(20)
/*SIP5_EPCL_ACTION_TABLE_FIELDS_TM_QUEUE_ID_E                               *//*123*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(0)/*field removed*/
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_PHA_METADATA_ASSIGN_ENABLE_E             *//*123*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_PHA_METADATA_E                           *//*124*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(32)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_PHA_THREAD_NUMBER_ASSIGN_ENABLE_E        *//*156*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_PHA_THREAD_NUMBER_E                      *//*157*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(8)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_EGRESS_MIRRORING_MODE_E                  *//*165*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(2)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_EGRESS_ANALYZER_INDEX_E                  *//*167*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(3)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_CPU_CODE_E                               *//*170*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(8)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_LATENCY_PROFILE_E                        *//*178*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(9)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_LATENCY_MONITORING_ENABLE_E              *//*187*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_CUT_THROUGH_TERMINATE_ID_E               *//*188*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_RESERVED_E                               *//*189-245*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(57)
/*   SIP6_EPCL_ACTION_TABLE_FIELDS_EXACT_MATCH_OVER_PCL_ENABLE_E            *//*246*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
};


static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6EgfQagPortSourceAttributesTableFieldsFormat[
    SIP5_20_EGF_QAG_PORT_SOURCE_ATTRIBUTES_TABLE_FIELDS___LAST_VALUE___E] =
{
    /*SIP5_20_EGF_QAG_PORT_SOURCE_ATTRIBUTES_TABLE_FIELDS_SOURCE_PHYSICAL_PORT_LOOPBACK_PROFILE_E       */
    PRV_CPSS_STANDARD_FIELD_MAC(2)
    /*SIP5_20_EGF_QAG_PORT_SOURCE_ATTRIBUTES_TABLE_FIELDS_SOURCE_PHYSICAL_PORT_TC_PROFILE_E             */
   ,PRV_CPSS_STANDARD_FIELD_MAC(2)
    /*SIP6_EGF_QAG_PORT_SOURCE_ATTRIBUTES_TABLE_FIELDS_SOURCE_PHYSICAL_PORT_SPEED_E                     */
   ,PRV_CPSS_STANDARD_FIELD_MAC(5)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6EgfQagTargetPortMapperTableFieldsFormat[
    SIP5_EGRESS_EGF_QAG_TARGET_PORT_MAPPER_TABLE_FIELDS___LAST_VALUE___E] =
{
/*    SIP5_EGRESS_EGF_QAG_TARGET_PORT_MAPPER_TABLE_FIELDS_PORT_BASE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(10),
/*    ,SIP6_EGRESS_EGF_QAG_TARGET_PORT_MAPPER_TABLE_FIELDS_PORT_SPEED_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(5)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6HaPhysicalPort2TableFieldsFormat[
    SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS____LAST_VALUE___E] =
{
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_CASCADE_PORT_ENABLE                          */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_EGRESS_DSA_TAG_TYPE                          */
    PRV_CPSS_STANDARD_FIELD_MAC(2),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_SER_CHECK_ENABLE                             */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_DISABLE_CRC_ADDING                           */
    PRV_CPSS_STANDARD_FIELD_MAC(0), /* field was removed in SIP6 */
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_RETAIN_EXTERNAL_CRC                          */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_PACKET_ID_ENABLE                             */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_ROUTED_SRC_DEVICE_ID_PORT_MODE_ENABLE_E      */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_SET_SOURCE_TO_LOCAL                          */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_LOCAL_DEVICE_NUMBER                          */
    PRV_CPSS_STANDARD_FIELD_MAC(12),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_LOCAL_SOURCE_ID                              */
    PRV_CPSS_STANDARD_FIELD_MAC(12),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_EPCL_TO_ANALYZER_PACKETS_PORT_ENABLE         */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_EPCL_TO_CPU_PACKETS_PORT_ENABLE              */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_PTP_TIMESTAMP_TAG_MODE                       */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_INVALID_CRC_MODE                             */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_TIMESTAMP_RECEPTION_EN                       */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_TRUNK_ID                                     */
    PRV_CPSS_STANDARD_FIELD_MAC(12),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_FORCE_NEW_DSA_TO_CPU                         */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_FORCE_NEW_DSA_FORWARD_OR_FROM_CPU            */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_PRE_PEND_TWO_BYTES_HEADER_EN                 */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_DSA_QOS_MODE                                 */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_REMOTE_PHYSICAL_PORT_MAP_ENABLE              */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_REMOTE_PHYSICAL_PORT_NUMBER                  */
    PRV_CPSS_STANDARD_FIELD_MAC(10),/* was 8 in previous device*/
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_REMOTE_PHYSICAL_PORT_DEVICE_ID               */
    PRV_CPSS_STANDARD_FIELD_MAC(12),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_TRANS_FWD_TO_4B_FROM_CPU_DSA_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_TRANS_TO_ANALYZER_TO_4B_FROM_CPU_DSA_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_TRANS_FROM_CPU_TO_4B_FROM_CPU_DSA_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/* SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_INSERT_HASH_INTO_FORWARD_DSA_ENABLE_E */
    PRV_CPSS_STANDARD_FIELD_MAC(1)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6EgfShtEgressEVlanAttributesTableFieldsFormat[
    SIP5_EGRESS_EGF_SHT_EGRESS_EVLAN_ATTRIBUTES_TABLE_FIELDS___LAST_VALUE___E]=
{
/*    ,SIP5_EGRESS_EGF_SHT_EGRESS_EVLAN_ATTRIBUTES_TABLE_FIELDS_LOCAL_SWITHING_EN_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*    ,SIP5_EGRESS_EGF_SHT_EGRESS_EVLAN_ATTRIBUTES_TABLE_FIELDS_PORT_ISOLATION_VLAN_CMD_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(2),
/*    ,SIP5_EGRESS_EGF_SHT_EGRESS_EVLAN_ATTRIBUTES_TABLE_FIELDS_EGRESS_MIRROR_TO_ANALYZER_INDEX_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*    ,SIP6_EGRESS_EGF_SHT_EGRESS_EVLAN_ATTRIBUTES_TABLE_FIELDS_EGRESS_MIRRORING_MODE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(2)/*sip6 : new field */
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6EgfQagEgressEPortTableFieldsFormat[
    SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS___LAST_VALUE___E] =
{
/*    SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_DP_TO_CFI_REMAP_ENABLE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_EGRESS_MIRROR_TO_ANALYZER_INDEX_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_EPORT_TAG_STATE_MODE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_EPORT_TAG_STATE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_EVLAN_COMMAND_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_VID1_COMMAND_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_UP0_COMMAND_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_UP1_COMMAND_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_EVLAN_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(13),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_VID1_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(12),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_UP0_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_UP1_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(3),
/*    ,SIP5_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_REMOVE_VLAN_TAG_1_IF_RX_WITHOUT_TAG_1_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
/*    ,SIP6_EGRESS_EGF_QAG_EGRESS_EPORT_TABLE_FIELDS_EGRESS_MIRRORING_MODE_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(2)/*sip6 : new field */
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6PlrMeteringConfigurationTableFieldsFormat[
    SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS___LAST_VALUE___E]=
{
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_COLOR_MODE_E                                   */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_POLICER_MODE_E                                 */
    PRV_CPSS_STANDARD_FIELD_MAC(3),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_MG_COUNTERS_SET_EN_E                           */
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_BILLING_PTR_E                                  */
    PRV_CPSS_STANDARD_FIELD_MAC(17),/*was 16 in sip5_15 */
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_BYTE_OR_PACKET_COUNTING_MODE_E                 */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_PACKET_SIZE_MODE_E                             */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_TUNNEL_TERMINATION_PACKET_SIZE_MODE_E          */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_INCLUDE_LAYER1_OVERHEAD_E                      */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_DSA_TAG_COUNTING_MODE_E                        */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_TIMESTAMP_TAG_COUNTING_MODE_E                  */
    PRV_CPSS_STANDARD_FIELD_MAC(1),

    /* ingress only fields */

    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_INGRESS_RED_CMD_E                              */
    {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
    2,
    SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_TIMESTAMP_TAG_COUNTING_MODE_E},
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_INGRESS_YELLOW_CMD_E                           */
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_INGRESS_GREEN_CMD_E                            */
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_INGRESS_MODIFY_DSCP_E                          */
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_INGRESS_MODIFY_UP_E                            */
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_INGRESS_QOS_PROFILE_E                          */
    PRV_CPSS_STANDARD_FIELD_MAC(10),

    /* egress only fields */

    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_EGRESS_REMARK_MODE_E                           */
    {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
    1,
    SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_TIMESTAMP_TAG_COUNTING_MODE_E},
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_EGRESS_DROP_RED_E                              */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_EGRESS_EN_MODIFY_EXP_E                         */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_EGRESS_EN_MODIFY_DSCP_E                        */
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_EGRESS_EN_MODIFY_TC_E                          */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_EGRESS_EN_MODIFY_UP_E                          */
    PRV_CPSS_STANDARD_FIELD_MAC(2),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_EGRESS_EN_MODIFY_DP_E                          */
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_EGRESS_EN_YELLOW_ECN_MARKING_E                 */
    PRV_CPSS_STANDARD_FIELD_MAC(1),

    /* field common to ingress and to egress */

    /*SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_MEF_10_3_ENV_SIZE_E                           */
    {PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
    3,
    SIP5_15_PLR_METERING_CONFIG_TABLE_FIELDS_INGRESS_QOS_PROFILE_E},
    /* SIP_6_PLR_METERING_CONFIG_TABLE_FIELDS_GREEN_MIRROR_EN_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /* SIP_6_PLR_METERING_CONFIG_TABLE_FIELDS_YELLOW_MIRROR_EN_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1),
    /* SIP_6_PLR_METERING_CONFIG_TABLE_FIELDS_RED_MIRROR_EN_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1)
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6ExactMatchTableFieldsFormat[SIP6_EXACT_MATCH_TABLE_FIELDS___LAST_VALUE___E] =
{

    /*SIP6_EXACT_MATCH_TABLE_FIELDS_VALID_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1)
    /*SIP6_EXACT_MATCH_TABLE_FIELDS_ENTRY_TYPE_E*/
    ,PRV_CPSS_STANDARD_FIELD_MAC(1)
        /* SIP6_EXACT_MATCH_TABLE_FIELDS_AGE_E */
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
        1,
        SIP6_EXACT_MATCH_TABLE_FIELDS_ENTRY_TYPE_E}
        /* SIP6_EXACT_MATCH_TABLE_FIELDS_KEY_SIZE_E */
       ,PRV_CPSS_STANDARD_FIELD_MAC(2)
        /* SIP6_EXACT_MATCH_TABLE_FIELDS_LOOKUP_NUM_E */
       ,PRV_CPSS_STANDARD_FIELD_MAC(1)
        /* SIP6_EXACT_MATCH_TABLE_FIELDS_KEY_E */
        ,PRV_CPSS_STANDARD_FIELD_MAC(40)
        /* SIP5_EXACT_MATCH_TABLE_FIELDS_REDUCE_ACTION_E */
        ,PRV_CPSS_STANDARD_FIELD_MAC(68)

        /* SIP6_EXACT_MATCH_TABLE_FIELDS_KEY_ONLY_E */
        ,{PRV_CPSS_FIELD_SET_IN_RUNTIME_CNS,
        112,
        SIP6_EXACT_MATCH_TABLE_FIELDS_ENTRY_TYPE_E}
};

static PRV_CPSS_ENTRY_FORMAT_TABLE_STC prvCpssDxChSip6EgfShtEgressEVlanTableFieldsFormat_maxPorts_mode[
    SIP5_EGRESS_EGF_SHT_EGRESS_EVLAN_TABLE_FIELDS___LAST_VALUE___E]=
{
/*     SIP5_EGRESS_EGF_SHT_EGRESS_EVLAN_TABLE_FIELDS_VALID_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(0),
/*    ,SIP5_EGRESS_EGF_SHT_EGRESS_EVLAN_TABLE_FIELDS_PORT_X_MEMBER_E*/
    PRV_CPSS_STANDARD_FIELD_MAC(1024)/* use single mode (max 1024) ... regardless to actual mode */
};


/**
* @internal fdb_initTablesDbSip6 function
* @endinternal
*
* @brief   init the Sip6 tables info
*/
static GT_STATUS fdb_initTablesDbSip6
(
    void
)
{
    GT_STATUS   rc;
    GT_U32      ii;
    SIP5_FDB_AU_MSG_TABLE_FIELDS_ENT    sip5Field;
    SIP6_FDB_AU_MSG_TABLE_FIELDS_ENT    sip6Field;

    static GT_BOOL initDone = GT_FALSE;


    if(initDone == GT_TRUE)
    {
        /* already init */
        return GT_OK;
    }

    initDone = GT_TRUE;

    if(prvCpssDxchFalconCiderVersionGet() < PRV_CPSS_DXCH_FALCON_CIDER_VERSION_18_06_06_E/*former18_04_22*/)
    {
        /* the field SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_REMOTE_PHYSICAL_PORT_NUMBER_E is 2 bits less */
        prvCpssDxChSip6HaPhysicalPort2TableFieldsFormat[SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_REMOTE_PHYSICAL_PORT_NUMBER_E          ].numOfBits -= 2;
        prvCpssDxChSip6HaPhysicalPort2TableFieldsFormat[SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_REMOTE_PHYSICAL_PORT_DEVICE_ID_E       ].startBit  -= 2;
        prvCpssDxChSip6HaPhysicalPort2TableFieldsFormat[SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_TRANS_FWD_TO_4B_FROM_CPU_DSA_E         ].startBit  -= 2;
        prvCpssDxChSip6HaPhysicalPort2TableFieldsFormat[SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_TRANS_TO_ANALYZER_TO_4B_FROM_CPU_DSA_E ].startBit  -= 2;
        prvCpssDxChSip6HaPhysicalPort2TableFieldsFormat[SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_TRANS_FROM_CPU_TO_4B_FROM_CPU_DSA_E    ].startBit  -= 2;
        prvCpssDxChSip6HaPhysicalPort2TableFieldsFormat[SIP5_HA_PHYSICAL_PORT_TABLE_2_FIELDS_INSERT_HASH_INTO_FORWARD_DSA_ENABLE_E  ].startBit  -= 2;
    }


    /* needed for : PRV_CPSS_DXCH_TABLE_FORMAT_FDB_AU_MSG_E */
    /* init the 'real' SIP6 table */
    rc = prvCpssFillFieldsStartBitInfo(NUM_ELEMENTS_IN_ARR_MAC(prvCpssDxChSip6FdbAuMsgTableFieldsFormat),
                                       prvCpssDxChSip6FdbAuMsgTableFieldsFormat);
    if(rc != GT_OK)
    {
        return rc;
    }

    cpssOsMemSet(&prvCpssDxChSip5_emulate_Sip6FdbAuMsgTableFieldsFormat,0,
        sizeof(prvCpssDxChSip5_emulate_Sip6FdbAuMsgTableFieldsFormat));

    for(ii = 0; convertSip5ToSip6FdbAuMsgArr[ii].sip5Field != SIP5_10_FDB_AU_MSG_TABLE_FIELDS___LAST_VALUE___E;
        ii++)
    {
        sip5Field = convertSip5ToSip6FdbAuMsgArr[ii].sip5Field;
        sip6Field = convertSip5ToSip6FdbAuMsgArr[ii].sip6Field;

        if(sip6Field == NOT_VALID_FIELD_CNS)
        {
            /* invalidate the info in SIP5 because no such field in SIP6 */
            /* NOTE: the numOfBits = 0 already from the 'cpssOsMemSet' */
            continue;
        }

        /* copy info from sip6 info */
        prvCpssDxChSip5_emulate_Sip6FdbAuMsgTableFieldsFormat[sip5Field] =
            prvCpssDxChSip6FdbAuMsgTableFieldsFormat[sip6Field];
    }


    return GT_OK;
}


/**
* @internal initTablesDbSip6 function
* @endinternal
*
* @brief   init the Sip6 tables info
*
* @param[in] devNum                   - device number
*                                       NONE
*/
GT_STATUS initTablesDbSip6
(
    IN GT_U8                devNum
)
{
    GT_STATUS   rc;
    PRV_CPSS_DXCH_PP_TABLE_FORMAT_INFO_STC * initTablesFormatPtr;

    initTablesFormatPtr = PRV_CPSS_DXCH_PP_MAC(devNum)->tableFormatInfo;

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_FDB_E ,
        prvCpssDxChSip6FdbFdbTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_FDB_AU_MSG_SIP6_DIFF_E ,
        prvCpssDxChSip6FdbAuMsgTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_FDB_AU_MSG_E ,
        prvCpssDxChSip5_emulate_Sip6FdbAuMsgTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_BRIDGE_INGRESS_EVLAN_E ,
        prvCpssDxChSip6L2iIngressVlanTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_EGF_QAG_PORT_TARGET_ATTRIBUTES_E ,
        prvCpssDxChSip6EgfQagPortTargetAttributesTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_TTI_PHYSICAL_PORT_ATTRIBUTE_E,
        prvCpssDxChSip6TtiPhysicalPortTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr,
        PRV_CPSS_DXCH_TABLE_FORMAT_PREQ_PORT_PROFILE_E,
        prvCpssDxChSip6PreqPortProfileTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr,
        PRV_CPSS_DXCH_TABLE_FORMAT_PREQ_PROFILES_E,
        prvCpssDxChSip6PreqProfilesTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr,
        PRV_CPSS_DXCH_TABLE_FORMAT_PREQ_QUEUE_CONFIGURATIONS_E,
        prvCpssDxChSip6PreqQueueConfigurationsTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr,
        PRV_CPSS_DXCH_TABLE_FORMAT_PREQ_QUEUE_PORT_MAPPING_E,
        prvCpssDxChSip6PreqQueuePortMappingTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr,
        PRV_CPSS_DXCH_TABLE_FORMAT_PREQ_QUEUE_PRIO_MAPPING_E,
        prvCpssDxChSip6PreqQueuePrioMappingTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr,
        PRV_CPSS_DXCH_TABLE_FORMAT_PREQ_TARGET_PHYSICAL_PORT_E,
        prvCpssDxChSip6PreqTargetPhysicalPortFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr,
        PRV_CPSS_DXCH_TABLE_FORMAT_EPCL_ACTION_E ,
        prvCpssDxChSip6EpclActionTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr,
        PRV_CPSS_DXCH_TABLE_FORMAT_IPCL_ACTION_E ,
        prvCpssDxChSip6IpclActionTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr,
        PRV_CPSS_DXCH_TABLE_FORMAT_EGF_QAG_PORT_SOURCE_ATTRIBUTES_E ,
        prvCpssDxChSip6EgfQagPortSourceAttributesTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_EGF_QAG_TARGET_PORT_MAPPER_E ,
        prvCpssDxChSip6EgfQagTargetPortMapperTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_HA_PHYSICAL_PORT_2_E ,
        prvCpssDxChSip6HaPhysicalPort2TableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_EGF_SHT_VLAN_ATTRIBUTES_E ,
        prvCpssDxChSip6EgfShtEgressEVlanAttributesTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_EGF_QAG_EGRESS_EPORT_E ,
        prvCpssDxChSip6EgfQagEgressEPortTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
        PRV_CPSS_DXCH_TABLE_FORMAT_PLR_METER_CONFIG_E ,
        prvCpssDxChSip6PlrMeteringConfigurationTableFieldsFormat);


    /* need to be called to fill prvCpssDxChSip5_emulate_Sip6FdbAuMsgTableFieldsFormat
       with proper values */
    rc = fdb_initTablesDbSip6(/*void*/);
    if(rc != GT_OK)
    {
        return rc;
    }

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
    PRV_CPSS_DXCH_TABLE_FORMAT_EXACT_MATCH_E ,
    prvCpssDxChSip6ExactMatchTableFieldsFormat);

    BIND_FIELDS_FORMAT_TO_TABLE_MAC(initTablesFormatPtr ,
    PRV_CPSS_DXCH_TABLE_FORMAT_EGF_SHT_EGRESS_EVLAN_E ,
    prvCpssDxChSip6EgfShtEgressEVlanTableFieldsFormat_maxPorts_mode);

    return GT_OK;
}


