#! /bin/bash

source $(dirname $0)/sh_funcs/include

prog_name=$(basename $0)

usage () {
echo "Usage:
NAME
       043_sfp_tx_disable - Verify tx-disable with transceiver

SYNOPSIS
       043_sfp_tx_disable [-t low/high]
                          [-h]

DESCRIPTION
       This command is used to verify functionality of tx-disable pin.
       The tx-disable pin value will be alter by CPLD, and verify the
       value on the transceiver side.

MANDATORY OPTIONS
       At least one optional option is needed.

OPTIONAL OPTIONS
       -t    test tx-disable pin
             value:
                 0: low
                 1: high

       -g    get tx-disable pin value

       -h    Help message

PASS CRITERIA
       - Control tx-disable pin(-t) :
           SUCCESS: tx-disable could be controlled
             Display: PASS
             Return code : 0

           ERROR: tx-disable couldn't be controlled
             Display: FAIL
             Return code : 2
           ERROR: invalid argument
             Display: FAIL
             Return code : 3

       - No transceiver insert
           ERROR: present pin value is 0
             Display: FAIL
             Return code : 4

       - Wrong Option
           ERROR: input option is none or not matching OPTIONAL OPTIONS
             Display: FAIL
             Return code : 1
EXAMPLE
       043_sfp_tx_disable -t 0
       043_sfp_tx-disable -g
       043_sfp_tx_disable -h
" >&2
}

get_sfp_txdisable () {
    local check=`i2cget -f -y $1 0x51 0x6e | sed s/0x//g`
    check=`hex2bin ${check}`
    check=`echo ${check::1}`
    echo ${check}
}

hex2bin() {
    local hex=$1
    local num=$((16#$hex))

    echo ${D2B[${num}]}
}

check_sku () {
    # check sku
    if [ ${sku} = "OS6360-P48X" ] || [ ${sku} = "OS6360-P24X" ] \
    || [ ${sku} = "OS6360-PH24" ]; then
        sfp_portnum=4

    elif [ ${sku} = "OS6360-10" ] || [ ${sku} = "OS6360-P10" ]; then
        sfp_portnum=2
    else
        echo
        echo "======================================"
        print_fail "sku not exist"
        echo "======================================"
        quit 4
    fi
}

#====================================================================
# variable define.

# result status.
result=${PASS}

# present south interface.
sysfs_present="/sys/bus/i2c/devices/0-007f/sfp_plus_present_"

# tx-disable south interface.
sysfs_txdisable="/sys/bus/i2c/devices/0-007f/tx_disable_"

# sfp portnumber.
sfp_portnum=2

# sku
sku=`cat /usr/local/sku`

# Dec to Binary.
D2B=({0..1}{0..1}{0..1}{0..1}{0..1}{0..1}{0..1}{0..1})

# test_mode status.
test_mode=false
read_mode=false

#====================================================================

if [ $# -lt 1 ]; then
    usage
    quit 1
fi

while getopts ":t:gh" arg
do
    case ${arg} in
        t)
            test_mode=true
            input_value=${OPTARG}
            ;;
        g)
            read_mode=true
            ;;
        h)
            usage
            quit_ok
            ;;
        *)
            usage
            quit 1
            ;;
    esac
done

if [ ${OPTIND} -eq 1 ]; then
    quit 1
fi

check_sku

if [ ${test_mode} = true ]; then
    insert_count=0

    # check if arg is an integer between 0-1.
    check_arg=`echo ${input_value} | grep '^[0-1]\{1\}$'`
    if [ -z ${check_arg} ]; then
        echo
        echo "======================================"
        print_fail "Invalid argument"
        echo "======================================"
        quit 3
    fi

    for (( i=0; i<${sfp_portnum}; i++ ))
    do
        echo
        echo "==========================================="

        value_present=`cat ${sysfs_present}${i}`
        if [ ${value_present} = "0x1" ]; then
            i2cset -f -y $((${i}+1)) 0x51 0x6f 0x92 > /dev/null 2>&1

            # set tx-disable value.
            echo ${input_value} > ${sysfs_txdisable}${i}

            check_txdisable_cpld=`cat ${sysfs_txdisable}${i}`
            check_txdisable_sfp=`get_sfp_txdisable $((${i}+1))`

            if [ ${check_txdisable_cpld} != "0x${input_value}" ] || \
            [ "0x${check_txdisable_sfp}" != "0x${input_value}" ]; then
                print_fail "sfp port ${i}:set tx-disable to ${input_value} fail"
                result=2
            else
                print_pass "sfp port ${i}:set tx-disable to ${input_value} success"
            fi

            insert_count=$((${insert_count}+1))
        else
            echo "sfp port ${i}: No transceiver insert"
        fi

        echo "==========================================="
    done

    if [ ${insert_count} -ne ${sfp_portnum} ]; then
        result=4
    fi
fi

if [ ${read_mode} = true ]; then
    insert_count=0

    for (( i=0; i<${sfp_portnum}; i++ ))
    do
        echo
        echo "==========================================="

        value_present=`cat ${sysfs_present}${i}`
        if [ ${value_present} = "0x1" ]; then

            check_txdisable_cpld=`cat ${sysfs_txdisable}${i}`

            echo "sfp port ${i}: tx-disable pin value is ${check_txdisable_cpld}"

            insert_count=$((${insert_count}+1))
        else
            echo "sfp port ${i}: No transceiver insert"
        fi

        echo "==========================================="
    done

    if [ ${insert_count} -ne ${sfp_portnum} ]; then
        result=4
    fi
fi

quit ${result}
